### PR TITLE
The jsp can now use the zeros parameter when joint names have slashes.

### LINKED ISSUE #59: zeros parameter when joint names have slashes
When a joint name has a slash in it (e.g. `robot1/joint_1`) it (at least seems) impossible to set the zero position using the zeros parameter.   I believe this is because of how the ros parameter server collapses dictionary keys.

For example,  `rosparam set zeros "{robot1/joint_1 : 1, robot1/joint_2 : 2}"` results in the parameters
`zeros/robot1/joint_1` and `zeros/robot1/joint_2` and as currently implemented the jsp is looking for `zeros['robot1/joint_1']`.

### PR DESCRIPTION
**Pull request by m-elwin**
fixes ros/joint_state_publisher#59

zeros should be a dictionary of joint-name joint-value pairs.  However,
the ROS parameter server expands dictionary keys into namespaces.

For example, rosparam set zeros "{joint_1 : 1.0, robot1/joint_2 : 2.0}" results
in the creation of two parameters: zeros/joint_1, zeros/robot1/joint_2.

This change causes the zeros value for a joint called "robot1/joint_2" to be read
from "zeros/robot1/joint_2".

### CODE REVIEW

**Comment by DLu** [comment]
I added commits here to round out this PR: https://github.com/m-elwin/joint_state_publisher/pull/1

**Comment by DLu** [comment]
@clalancette You want to check this out?

**Comment by mintar** [comment]
+1 for this PR.

In the long run, it would be nice to fix this in the parameter server instead. IMO, that's where the real bug is, because the parameter server should allow escaping "/" characters. Instead, it ignores any `"`, `'` and `\` chars that you put into your YAML to mark a string.

**Comment by DLu** [comment]
Accio @clalancette !

**Review by clalancette — APPROVED** [review]

**Pull request merged**
